### ISSUE TITLE
pxd 安装tryout 报错

### ISSUE THREAD

**Issue by mahuilong2020** [polardb/polardbx-operator#23]
os:centos-stream 9 
docker version 24

python version: 3.9

pxd version: 0.5.3

报错如下：
latest:Pulling from polardbx/xstore-tools 
Digest: sha256:745a19864eb6ef05a07b8ba97bc428aa9ed9084784f93a48e3c8a3c4e16a1f28
Status: Image is up to date for polardbx/xstore-tools:latest
Pull image: polardbx/polardbx-cdc:latest at 127.0.0.1

latest:Pulling from polardbx/polardbx-cdc 
Digest: sha256:d372291c367309016b3a273d2feaa619c592712c3f54478d8c47425bae83efcf
Status: Image is up to date for polardbx/polardbx-cdc:latest
Processing  [###########-------------------------]   30%    create gms node
Processing  [#############-----------------------]   38%    create gms db and tables
Processing  [################--------------------]   46%    create PolarDB-X root account
Processing  [###################-----------------]   53%    create dn

Traceback (most recent call last):
  File "/home/polardbx/.local/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/polardbx/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.43/containers/41ce7473fd94b6d9e7ef1247bd8ce4c36d5d6bdbaf762d7260c7f1dbcf472d95/exec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/polardbx/.local/bin/pxd", line 8, in <module>
    sys.exit(main())
  File "/home/polardbx/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/polardbx/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/polardbx/.local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/polardbx/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/polardbx/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/pxd.py", line 53, in tryout
    create_tryout_pxc(name, cn_replica, cn_version, dn_replica, dn_version, cdc_replica, cdc_version, leader_only)
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/pxc/polardbx_manager.py", line 36, in create_tryout_pxc
    pxc.create()
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/pxc/polardbx_cluster.py", line 144, in create
    result = create_task()
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/decorator/decorators.py", line 40, in wrapper
    raise ex
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/decorator/decorators.py", line 33, in wrapper
    ret = func(*args, **kw)
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/pxc/polardbx_cluster.py", line 353, in _create_dn
    logger.info(f.result())
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/pxc/polardbx_cluster.py", line 342, in _create_dn
    xdb.create()
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/xdb/xdb.py", line 100, in create
    result = create_task()
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/decorator/decorators.py", line 61, in wrapper
    raise ex
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/decorator/decorators.py", line 54, in wrapper
    ret = func(*args, **kw)
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/xdb/xdb.py", line 397, in _create_admin_account
    leader_node = self._wait_leader_elected()
  File "/home/polardbx/.local/lib/python3.9/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/polardbx/.local/lib/python3.9/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/home/polardbx/.local/lib/python3.9/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/polardbx/.local/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/polardbx/.local/lib/python3.9/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/polardbx/.local/lib/python3.9/site-packages/deployer/xdb/xdb.py", line 358, in _wait_leader_elected
    (exit_code, output) = container.exec_run(cmd=["/tools/xstore/current/venv/bin/python3",
  File "/home/polardbx/.local/lib/python3.9/site-packages/docker/models/containers.py", line 193, in exec_run
    resp = self.client.api.exec_create(
  File "/home/polardbx/.local/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/polardbx/.local/lib/python3.9/site-packages/docker/api/exec_api.py", line 80, in exec_create
    return self._result(res, True)
  File "/home/polardbx/.local/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/polardbx/.local/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/polardbx/.local/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.43/containers/41ce7473fd94b6d9e7ef1247bd8ce4c36d5d6bdbaf762d7260c7f1dbcf472d95/exec: Conflict ("Container 41ce7473fd94b6d9e7ef1247bd8ce4c36d5d6bdbaf762d7260c7f1dbcf472d95 is not running")

**Comment by vettalwu** [comment]
@mahuilong2020 It seems that DN container is not running. Please login the DN host, exec `docker ps -a | grep 41ce7473fd` to check the container status.

**Comment by mahuilong2020** [comment]
docker logs 

/tools/xstore/current/venv/lib64/python3.6/site-packages/pymysql/_auth.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
2023-07-24 14:21:12,431 - GalaxyEngine - INFO - begin wait for enable
2023-07-24 14:21:17,437 - GalaxyEngine - INFO - finish wait for enable
INFO:root:Begin to initialize...
2023-07-24 14:21:17,465 - GalaxyEngine - INFO - () start command: /usr/bin/ln -sf /data/mysql-log/log /data/mysql/log
2023-07-24 14:21:17,479 - GalaxyEngine - INFO - succeeding to exec cmd ['/usr/bin/ln', '-sf', '/data/mysql-log/log', '/data/mysql/log'] 
2023-07-24 14:21:17,481 - GalaxyEngine - INFO - (cwd=/data/mysql/data) execute command: /opt/galaxy_engine/bin/mysqld --defaults-file=/data/mysql/conf/my.cnf --loose-pod-name=pxc-tryout-gms-Cand-17112 --loose-cluster-info=172.17.0.2:25112@1 --initialize-insecure
Traceback (most recent call last):
  File "/tools/xstore/current/entrypoint.py", line 119, in <module>
    _start()
  File "/tools/xstore/current/venv/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tools/xstore/current/venv/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tools/xstore/current/venv/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tools/xstore/current/venv/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tools/xstore/current/entrypoint.py", line 99, in _start
    engine.initialize()
  File "/tools/xstore/v1.4.0-1681277870.050488/core/engine/galaxy/engine.py", line 151, in initialize
    self._initialize_data()
  File "/tools/xstore/v1.4.0-1681277870.050488/core/engine/galaxy/engine.py", line 141, in _initialize_data
    stderr=sys.stderr
  File "/tools/xstore/v1.4.0-1681277870.050488/core/engine/engine.py", line 324, in check_run_process
    return subprocess.check_call(cmd, cwd=cwd, stdout=stdout, stderr=stderr, env=self.context.subprocess_envs())
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/galaxy_engine/bin/mysqld', '--defaults-file=/data/mysql/conf/my.cnf', '--loose-pod-name=pxc-tryout-gms-Cand-17112', '--loose-cluster-info=172.17.0.2:25112@1', '--initialize-insecure']' died with <Signals.SIGKILL: 9>.

**Comment by vettalwu** [comment]
@mahuilong2020  Please check error message in the dn log. Log file path is: `~/.pxd/log/polarx-log/{ip}_{port}/log/alert.log`

**Comment by vettalwu** [comment]
DN initialize process is killed because of OOM according to dmesg. So increase the mem_limit of DN in pxd yaml file will solve this problem. 
![image](https://github.com/polardb/polardbx-operator/assets/92501707/c66028b9-8011-4539-a93d-ddf49bdd5e99)
