### ISSUE TITLE
Failed to install polardbx-operator in OrbStack

### ISSUE THREAD

**Issue by meiyese** [polardb/polardbx-operator#31]
Hi, we use https://orbstack.dev/ k8s environment for development

we install by `helm install --namespace polardbx-operator-system polardbx-operator polardbx/polardbx-operator`
with version v1.5.0

but `polardbx-hpfs` start failed with error message

```
2023-11-17T14:43:20.414Z	INFO	getting file lock...
2023-11-17T14:43:20.414Z	INFO	locked, continue
2023-11-17T14:43:20.414Z	INFO	starting grpc service...
2023-11-17T14:43:20.415Z	INFO	Start filestream server
Loading block devices...
failed to create local file service: stat /dev/vda: no such file or directory

```

**Comment by vettalwu** [comment]
@meiyese Does `/sys/fs/cgroup` exist in your k8s node?

**Comment by Cloud-Yao** [comment]
I meet same question, how to solve it on OrbStack Env ?

**Comment by kdrag0n** [comment]
OrbStack developer here. This error occurs because not all the block devices in `/sys/class/block` are in `/dev`. This can happen when Kubernetes is running in a container, so I'd recommend failing gracefully and skipping inaccessible block devices.

**Comment by vettalwu** [comment]
@meiyese @Cloud-Yao  I have built a temporary polardbx-operator hpfs image `polardbx/polardbx-hpfs:orbstack`, which skip the device not found error. Please update the image of hpfs to work around this issue.

```
kubectl edit daemonset polardbx-hpfs -n polardbx-operator-system
```

**Comment by Cloud-Yao** [comment]
<img width="1435" alt="image" src="https://github.com/polardb/polardbx-operator/assets/76988455/fb302725-f15d-4a20-ba3e-7449b84abf17">
I replace hpfs image , but still have an error, look at log . 
<img width="875" alt="image" src="https://github.com/polardb/polardbx-operator/assets/76988455/e4308f32-47d4-4210-80b9-ee70b558824c">

**Comment by vettalwu** [comment]
@Cloud-Yao Can you provide the file info in `/sys/block`, `/sys/class/block`, `/dev`

**Comment by meiyese** [comment]
Hi @vettalwu 

@kdrag0n says that they also "Added a workaround for the next version"
at Discord https://discord.gg/Tfjyd5N5Eq

**Comment by vettalwu** [comment]
> Hi @vettalwu
> 
> @kdrag0n says that they also "Added a workaround for the next version" at Discord https://discord.gg/Tfjyd5N5Eq

SGTM. Thanks @kdrag0n

**Comment by meiyese** [comment]
Hi @kdrag0n 

Thanks for your awesome job of OrbStack version 1.2.0

However, for some reason, errors are still reported in the latest 1.2.0 version.

```
2023-12-20T16:58:28.236Z	INFO	getting file lock...
2023-12-20T16:58:28.236Z	INFO	locked, continue
2023-12-20T16:58:28.236Z	INFO	starting grpc service...
2023-12-20T16:58:28.238Z	INFO	Start filestream server
Loading block devices...
failed to create local file service: stat /dev/vdc1: no such file or directory
```

**Comment by meiyese** [comment]
@vettalwu now start failed with command
```shell
echo "apiVersion: polardbx.aliyun.com/v1
kind: PolarDBXCluster
metadata:
  name: quick-start
  annotations:
    polardbx/topology-mode-guide: quick-start" | kubectl apply -f -
```

```
Defaulted container "engine" out of: engine, exporter, prober
/tools/xstore/current/venv/lib64/python3.6/site-packages/pymysql/_auth.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
2023-12-29 14:04:56,028 - GalaxyEngine - INFO - begin wait for enable
2023-12-29 14:05:01,042 - GalaxyEngine - INFO - finish wait for enable
INFO:root:Begin to initialize...
2023-12-29 14:05:01,062 - GalaxyEngine - INFO - (cwd=/data/mysql/data) execute command: /opt/galaxy_engine/bin/mysqld --defaults-file=/data/mysql/conf/my.cnf --loose-pod-name=quick-start-bjjf-gms-single-0 --loose-cluster-info=192.168.194.8:11306@1 --initialize-insecure
Traceback (most recent call last):
  File "/tools/xstore/current/entrypoint.py", line 124, in <module>
    _start()
  File "/tools/xstore/current/venv/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tools/xstore/current/venv/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tools/xstore/current/venv/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tools/xstore/current/venv/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tools/xstore/current/entrypoint.py", line 101, in _start
    engine.initialize()
  File "/tools/xstore/v1.5.0-1700478202.1760352/core/engine/galaxy/engine.py", line 151, in initialize
    self._initialize_data()
  File "/tools/xstore/v1.5.0-1700478202.1760352/core/engine/galaxy/engine.py", line 141, in _initialize_data
    stderr=sys.stderr
  File "/tools/xstore/v1.5.0-1700478202.1760352/core/engine/engine.py", line 333, in check_run_process
    return subprocess.check_call(cmd, cwd=cwd, stdout=stdout, stderr=stderr, env=self.context.subprocess_envs())
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/galaxy_engine/bin/mysqld', '--defaults-file=/data/mysql/conf/my.cnf', '--loose-pod-name=quick-start-bjjf-gms-single-0', '--loose-cluster-info=192.168.194.8:11306@1', '--initialize-insecure']' returned non-zero exit status 3.

```
